# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  restore:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/src/Tmuzik.Api
          name: Run restore
          command: |
            dotnet restore

             restore:
  build:
    docker:
    - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/src/Tmuzik.Api
          name: Run build
          command: |
            dotnet build
  deploy:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:2d:85:3d:ce:d2:36:41:95:fa:c6:1e:d3:87:20:dc"
      - run: ssh oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - restore
      - build
      - deploy
